export const registerTypes = {
  USER_REGISTER: "USER_REGISTER",
  USER_REGISTER_INIT: "USER_REGISTER_INIT",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};
