export const homeTypes = {
  GET_HOME_DATA: "GET_HOME_DATA",
  GET_HOME_DATA_SUCCESS: "GET_HOME_DATA_SUCCESS",
  GET_HOME_DATA_FAILURE: "GET_HOME_DATA_FAILURE",
  GET_HOME_DATA_INIT: "GET_HOME_DATA_INIT",
};
